### PR TITLE
Fixes that the JTI parent has fields from JTI's

### LINKED ISSUE #67: JTI parent has children fields
For thw 4.0 release we need to fix JTI/STI attributes harvesting.
That fix won't be applied for 4.0 but tests are useful https://github.com/cycle/annotated/pull/65

### PR DESCRIPTION
**Pull request by meekstellar**

### CODE REVIEW

File: src/TableInheritance.php [hunk 1]
```diff
@@ -133,6 +133,8 @@ private function initInheritance(
                 $parent->getInheritance()->setDiscriminator($annotation->getName());
             }
 
+            $parent->merge($entity);
```
Comment (roxblnfk) [inline src/TableInheritance.php:136]: Are there any tests about fields merging in case STI?

**Review by roxblnfk — APPROVED** [review]
